spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.docker.compose.enabled=false

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
stripe.app-url=${APP_URL}

telegram.botToken=${TELEGRAM_BOT_TOKEN}
telegram.botUsername=${TELEGRAM_BOT_USERNAME}
telegram.chatId=${TELEGRAM_CHAT_ID}
